project_id = "hzpjxqkbnfbvzcarttjb"

[functions.evaluate-experiment]
verify_jwt = false

[functions.analyze-experiments]
verify_jwt = false

[functions.fetch-google-sheet]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false

[functions.n8n-webhook-update]
verify_jwt = false
